version: "3"
volumes:
  mysql_data:
  redis_data:
  vendor_bundle:
  vendor_assets:
  node_modules:
  public_spree:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      redis:
        image: redis:alpine
        networks:
          - default
        ports:
          - '36379:6379'
        volumes:
          - redis_data:/var/lib/redis
  potepanec:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mysql
      - redis
    networks:
      - default
    volumes:
      - .:/potepanec
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /potepanec/log
      - /potepanec/tmp
      - vendor_bundle:/potepanec/vendor/bundle
      - vendor_assets:/potepanec/vendor/assets
      - node_modules:/potepanec/node_modules
      - public_spree:/potepanec/public/spree
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
